export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CHANGE_PROPOSAL_TITLE= 'CHANGE_PROPOSAL_TITLE';
export const CHANGE_PROPOSAL_DESCRIPTION= 'CHANGE_PROPOSAL_DESCRIPTION';
export const CHANGE_PROPOSAL_PARTNERCOMPANY= 'CHANGE_PROPOSAL_PARTNERCOMPANY';
export const CHANGE_PROPOSAL_APPROVER='CHANGE_PROPOSAL_APPROVER';