export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CHANGE_PROPOSAL_TITLE = 'CHANGE_PROPOSAL_TITLE';
export const CHANGE_PROPOSAL_DESCRIPTION = 'CHANGE_PROPOSAL_DESCRIPTION';
export const CHANGE_PROPOSAL_PARTNERCOMPANY = 'CHANGE_PROPOSAL_PARTNERCOMPANY';
export const CHANGE_PROPOSAL_APPROVER = 'CHANGE_PROPOSAL_APPROVER';
export const CHANGE_PROPOSAL_STATUS = 'CHANGE_PROPOSAL_STATUS';
export const GET_PROPOSALS = 'GET_PROPOSALS';
export const ADD_SECTION = 'ADD_SECTION';
export const GET_BIDS_SECTIONS = 'GET_BIDS_SECTIONS';
export const ADD_TITLE = 'ADD_TITLE';
export const CLEAR = 'CLEAR';
export const LOGIN = 'LOGIN';

export const GET_EMPLOYEE='GET_EMPLOYEE';
export const SHOW_COMMENT_FORM='SHOW_COMMENT_FORM';
export const SHOW_BID_FORM='SHOW_BID_FORM';
export const SHOW_REVIEW_FORM='SHOW_REVIEW_FORM';
export const SHOW_TEAMMEMBER_FORM='SHOW_TEAMMEMBER_FORM';
export const SHOW_SECTION_FORM='SHOW_SECTION_FORM';

export const GET_PROPOSAL_PARTNERS = 'GET_PROPOSAL_PARTNERS';
export const GET_PROPOSAL_STAFF = 'GET_PROPOSAL_STAFF';
export const GET_PROPOSAL_SECTIONS = 'GET_PROPOSAL_SECTIONS';
export const GET_PROPOSAL_COMMENTS = 'GET_PROPOSAL_COMMENTS';
export const GET_PROPOSAL_BIDS = 'GET_PROPOSAL_BIDS';
export const GET_PROPOSAL_REVIEWS = 'GET_PROPOSAL_REVIEWS';
export const GET_SINGLE_PROPOSAL ='GET_SINGLE_PROPOSAL';

export const ADD_PROPOSAL_COMMENT= 'ADD_PROPOSAL_COMMENT';
export const ADD_PROPOSAL_REVIEW='ADD_PROPOSAL_REVIEW';
export const ADD_PARTNER_MEMBER='ADD_PARTNER_MEMBER';
export const TYPE_OF_MEMBER='TYPE_OF_MEMBER';
export const ADD_STAFF_MEMBER='ADD_STAFF_MEMBER';
export const ADD_PROPOSAL_SECTION='ADD_PROPOSAL_SECTION';
export const SHOW_ADD_BID_BUTTON = 'SHOW_ADD_BID_BUTTON';

export const GET_BIDS='GET_BIDS';

export const CLEAR_BIDS='CLEAR_BIDS';
export const CLEAR_REVIEWS='CLEAR_REVIEWS';
