export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CHANGE_PROPOSAL_TITLE = 'CHANGE_PROPOSAL_TITLE';
export const CHANGE_PROPOSAL_DESCRIPTION = 'CHANGE_PROPOSAL_DESCRIPTION';
export const CHANGE_PROPOSAL_PARTNERCOMPANY = 'CHANGE_PROPOSAL_PARTNERCOMPANY';
export const CHANGE_PROPOSAL_APPROVER = 'CHANGE_PROPOSAL_APPROVER';
export const GET_PROPOSALS = 'GET_PROPOSALS';
export const ADD_SECTION = 'ADD_SECTION';
export const GET_BIDS = 'GET_BIDS';
export const ADD_TITLE = 'ADD_TITLE';
export const CLEAR = 'CLEAR';
export const LOGIN = 'LOGIN';

export const GET_EMPLOYEE='GET_EMPLOYEE';
export const SHOW_COMMENT_FORM='SHOW_COMMENT_FORM';
export const SHOW_BID_FORM='SHOW_BID_FORM';
export const SHOW_REVIEW_FORM='SHOW_REVIEW_FORM';
export const SHOW_TEAMMEMBER_FORM='SHOW_TEAMMEMBER_FORM';
export const SHOW_SECTION_FORM='SHOW_SECTION_FORM';

export const GET_PROPOSAL_PARTNERS = 'GET_PROPOSAL_PARTNERS';
export const GET_PROPOSAL_STAFF = 'GET_PROPOSAL_STAFF';
export const GET_PROPOSAL_SECTIONS = 'GET_PROPOSAL_SECTIONS';
export const GET_PROPOSAL_COMMENTS = 'GET_PROPOSAL_COMMENTS';
export const GET_PROPOSAL_BIDS = 'GET_PROPOSAL_BIDS';
export const GET_PROPOSAL_REVIEWS = 'GET_PROPOSAL_REVIEWS';

export const ADD_PROPOSAL_COMMENT= 'ADD_PROPOSAL_COMMENT';

